apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store         
  namespace: argocd             

spec:
  provider:
    aws:
      service: SecretsManager    
      region: eu-north-1          

      auth:
        secretRef:               

          accessKeyIDSecretRef:
            name: aws-creds      # Name of the Kubernetes Secret that contains your AWS credentials (must be created manually)
            key: access_key      # Key inside the Kubernetes Secret that contains the AWS access key ID

          secretAccessKeySecretRef:
            name: aws-creds      # Same Kubernetes Secret that also contains the secret access key
            key: secret_key      # Key inside the Kubernetes Secret that contains the AWS secret access key
